Draft: Update list command
AY2223S1-CS2103T-W16-2/tp pull request #151
Opened 2022-10-08 05:20 UTC by yixiann

Add DuplicateItemException.
Add ItemNotFoundException. 
Add UniqueItem List.

2022-10-10 05:34 UTC, bryanljx requested changes
Generally looks good. However, the auto formatting is messing up a lot of files and since AddressBook is changed to FoodRem, corresponding var names in these files should also be renamed to foodRem. 

Besides that, should be fine. I will continue reviewing after you fix these first. Left the changes to test cases to go.

2022-10-10 05:34 UTC, bryanljx commented on docs/DeveloperGuide.md
> +  original source as well}
The auto formatting messing the docs up again

2022-10-10 05:34 UTC, bryanljx commented on docs/tutorials/AddRemark.md
> +edit it if required. The command should have the following format:
Again, the auto formatting messing things up. Not impt here tho cuz this is the tutorial/add-remark part.

2022-10-10 05:34 UTC, bryanljx commented on docs/tutorials/TracingCode.md
> +* Table of Contents {:toc}
Ditto

2022-10-10 05:34 UTC, bryanljx commented on src/main/java/seedu/foodrem/commons/core/Config.java
> +        return "Current log level : " + logLevel + "\nPreference file Location : " + userPrefsFilePath;
Just curious, is there a reason for this change?

2022-10-10 05:34 UTC, bryanljx commented on src/main/java/seedu/foodrem/commons/core/GuiSettings.java
> +                + windowHeight + "\n" + "Position : " + windowCoordinates;
Ditto

2022-10-10 05:34 UTC, bryanljx commented on src/main/java/seedu/foodrem/commons/core/index/Index.java
> +            && zeroBasedIndex == ((Index) other).zeroBasedIndex); // state check
The auto formatting settings seem off. The style guide for cs2103t specifies 8 spaces for line breaks, not 4.

2022-10-10 05:34 UTC, bryanljx commented on src/main/java/seedu/foodrem/commons/core/index/Index.java
>   */
Need verify this but is the <p> needed for cs2103t style guide for javadocs?

2022-10-10 05:34 UTC, bryanljx commented on src/main/java/seedu/foodrem/commons/util/JsonUtil.java
> +     * @param filePath                   cannot be null.
Auto formatting again

2022-10-10 05:34 UTC, bryanljx commented on src/main/java/seedu/foodrem/commons/util/JsonUtil.java
> +     * @param <T>      The generic type to create an instance of
Auto formatting again

2022-10-10 05:34 UTC, bryanljx commented on src/main/java/seedu/foodrem/commons/util/StringUtil.java
> +     * @param word     cannot be null, cannot be empty, must be a single word
Auto formatting again

2022-10-10 05:34 UTC, bryanljx commented on src/main/java/seedu/foodrem/commons/util/StringUtil.java
> +            .anyMatch(preppedWord::equalsIgnoreCase);
Ditto

2022-10-10 05:34 UTC, bryanljx commented on src/main/java/seedu/foodrem/model/ModelManager.java
> +    private final FoodRem addressBook;
Please rename the variable name addressBook to foodRem as well

2022-10-10 05:34 UTC, bryanljx commented on src/main/java/seedu/foodrem/model/UserPrefs.java
> +        return "Gui Settings : " + guiSettings + "\nLocal data file location : " + addressBookFilePath;
Ditto

2022-10-10 05:34 UTC, bryanljx commented on src/main/java/seedu/foodrem/model/item/ItemBoughtDate.java
> +            && itemDate.equals(((ItemBoughtDate) other).itemDate)); // state check
Ditto

2022-10-10 05:34 UTC, bryanljx commented on src/main/java/seedu/foodrem/model/item/ItemBoughtDate.java
> +        return itemDate.toString();
Is `DATE_OUTPUT_PATTERN_REGEX` not used anymore?

2022-10-10 05:34 UTC, bryanljx commented on src/main/java/seedu/foodrem/model/item/ItemExpiryDate.java
> +            && itemDate.equals(((ItemExpiryDate) other).itemDate)); // state check
Ditto

2022-10-10 05:34 UTC, bryanljx commented on src/main/java/seedu/foodrem/model/item/ItemExpiryDate.java
> +        return itemDate.toString();
Ditto

2022-10-10 05:34 UTC, bryanljx commented on src/main/java/seedu/foodrem/model/item/itemvalidator/ItemBoughtDateValidator.java
> +        String.format("Year should be less than %d.", MAX_YEAR);
Ditto

2022-10-10 05:34 UTC, bryanljx commented on src/main/java/seedu/foodrem/model/util/SampleDataUtil.java
> +                new ItemExpiryDate("2022-11-11"))
Should create sample data with different expiry date from bought date. Possibly add some items that do not have expiry dates as well.

2022-10-11 10:34 UTC, yixiann commented
Duplicated : https://github.com/AY2223S1-CS2103T-W16-2/tp/pull/151

2022-10-11 10:34 UTC, closed without merging