Add Glossary section to User Guide
AY2223S1-CS2103T-W16-2/tp pull request #163
Opened 2022-10-11 16:23 UTC by Ferusel

Closes #87 

Adds the Glossary section to the User Guide.

2022-10-11 23:21 UTC, RichDom2185 requested changes
Please reconfigure your linter to not add hard line breaks in Markdown files. It violates the coding standard.

2022-10-12 00:21 UTC, Eugenetanwl3881 commented on docs/UserGuide.md
>  ## Glossary
Perhaps, including some of the technical terms present will be useful:

- Command line
- syntax
- parameters/arguments 

These are non-exhaustive. Add more if you think I have missed out any. If you think they have been specified clearly enough in the UG, it is fine to leave them out.

2022-10-12 02:19 UTC, Ferusel commented
I reverted the changes made from intelliJ's linter and used the markdown linter specified in #166. I also git push force'd following the [instructions here](https://github.com/AY2223S1-CS2103T-W16-2/tp/pull/166) FYI.

2022-10-12 04:00 UTC, RichDom2185 approved these changes
LGTM, thanks!

2022-10-12 04:03 UTC, merged